<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>FSharp.MinimalApi</RootNamespace>

        <Authors>Lucas Teles, Argyle Concepts</Authors>
        <Company>Argyle Concepts</Company>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/ArgyleConcepts/FSharp.MinimalApi</PackageProjectUrl>
        <RepositoryUrl>https://github.com/ArgyleConcepts/FSharp.MinimalApi</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <DocumentationFile>bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" Version="$(ArgyleFSharpCoreVersion)"/>
    </ItemGroup>
</Project>
