<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <IsPackable>true</IsPackable>
        <PackageId>ArgyleConcepts.FSharp.MinimalApi</PackageId>
        <PackageVersion>$(ArgylePackageVersion)</PackageVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Authors>Lucas Teles, Argyle Concepts</Authors>
        <Company>Argyle Concepts</Company>
        <Description>Easily use AspNet Core MinimalApi with F#</Description>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/ArgyleConcepts/FSharp.MinimalApi</PackageProjectUrl>
        <RepositoryUrl>https://github.com/ArgyleConcepts/FSharp.MinimalApi</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageTags>AspNet,Asp,fsharp,Minimal api,MinimalApi</PackageTags>
        <DocumentationFile>bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeInteropAssembly</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\LICENSE" Pack="true" PackagePath="\"/>
        <Compile Include="Constants.fs"/>
        <Compile Include="Extensions\Utils.fs"/>
        <Compile Include="Extensions\DI.fs"/>
        <Compile Include="Extensions\EndpointRouteBuilder.fs"/>
        <Compile Include="Builder\Produces.fs"/>
        <Compile Include="Builder\EndpointHandlerBuilder.fs"/>
        <Compile Include="Builder\EndpointsBuilder.fs"/>
        <Compile Include="Builder\Builders.fs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FSharp.MinimalApi.Interop\FSharp.MinimalApi.Interop.csproj" PrivateAssets="all" />
    </ItemGroup>

    <Target Name="IncludeInteropAssembly">
        <ItemGroup>
            <BuildOutputInPackage Include="$(OutputPath)FSharp.MinimalApi.Interop.dll" />
            <BuildOutputInPackage Include="$(OutputPath)FSharp.MinimalApi.Interop.pdb" Condition="Exists('$(OutputPath)FSharp.MinimalApi.Interop.pdb')" />
        </ItemGroup>
    </Target>

</Project>
